import React, {Attributes, useEffect, useState} from 'react';
import Head from 'next/head';
import MainLayout from '../../components/PagesComponents/MainLayout/MainLayout';
import {Grid} from '@mui/material';
import ProfileInfo from '../../components/PagesComponents/Profile/ProfileInfo';
import ProfilePosts from '../../components/PagesComponents/Profile/ProfilePosts';
import ProfileFriends from '../../components/PagesComponents/Profile/ProfileFriends';
import {useRouter} from 'next/router';
import {User} from 'parse';
import Parse from 'parse';
import {doQueryByName} from '../../parse/functions';

const UserPage = () => {
  const [queryResult, setQueryResult] = useState<string | null> ();
  const router = useRouter();
  console.log(queryResult);

  useEffect(() => {
    doQueryByName(router.query.username).then(data => setQueryResult(data));
  }, [])

  return (
    <div>
      <Head>
        <title>SocialApes</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        {/*{currentUser && (*/}
        {/*  <MainLayout>*/}
        {/*    <Grid container spacing={{ xs: 1, sm: 2, md: 3 }}>*/}
        {/*      <Grid item xs={12}>*/}
        {/*        <Grid container justifyContent='center'>*/}
        {/*          <Grid item xs={12} xl={8} >*/}
        {/*            <ProfileInfo currentUser={currentUser}/>*/}
        {/*          </Grid>*/}
        {/*        </Grid>*/}
        {/*      </Grid>*/}
        {/*      <Grid item xs={12}>*/}
        {/*        <Grid container spacing={{ xs: 1, sm: 2, md: 3 }} justifyContent='center' >*/}
        {/*          <Grid item xs={8} xl={5}>*/}
        {/*            <ProfilePosts currentUser={currentUser}/>*/}
        {/*          </Grid>*/}
        {/*          <Grid item xs={4} xl={3}>*/}
        {/*            <ProfileFriends/>*/}
        {/*          </Grid>*/}
        {/*        </Grid>*/}
        {/*      </Grid>*/}
        {/*    </Grid>*/}
        {/*  </MainLayout>*/}
        {/*)}*/}
        {`profile page ${queryResult}`}
      </main>
    </div>
  );
};

export default UserPage;