import type { NextPage } from 'next';
import Head from 'next/head';
import {Box, Paper} from '@mui/material';
import React from 'react';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Social Network</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Box
          sx={{
            bgcolor: 'background.default',
            width: '100%',
            height: '100vh',
            color: '#fff',
            display: 'flex',
            justifyContent: 'space-between'
          }}
        >
          <Paper elevation={6}
            sx={{
              boxShadow: 0,
              width: '20%',
              minWidth: '200px',
              padding: '2em',
              borderTopRightRadius: '30px',
              borderBottomRightRadius: '30px',
            }}>
            Paper
          </Paper>
          <Box sx={{
            height: '100%',
            width: '100%',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center'
          }}>
            Социальная сеть нового поколения
          </Box>
        </Box>
      </main>
    </div>
  )
}

export default Home
